[tool.poetry]
name = "llm_graph"
version = "0.1.0"
description = "Framework for LLM self-diagnosis and self-improve using graphs"
authors = ["Zhaochen Hong"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
bitsandbytes = "0.42.0"
peft = "0.8.2"
trl = "0.7.10"
accelerate = "0.27.1"
datasets = "2.17.0"
transformers = "4.38.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
